/* JANA BAZAR — standalone demo/prototype application.
   Data is persisted in localStorage so the site works immediately on GitHub Pages.
   Replace demo adapters with real backend/provider integrations before production. */
(function(){
  const KEY='jana_bazar_db_v1';
  const img='jana-bazar-logo.png';
  const seed={
    location:'Visakhapatnam',
    users:[], currentUser:null,
    products:[
      {id:'p1',name:'Organic Turmeric Powder 500g',category:'Farmer Products',seller:'Sri Lakshmi FPO',sellerType:'FPO',price:189,mrp:240,discount:21,rating:4.7,reviews:126,stock:84,location:'Visakhapatnam',image:'https://images.unsplash.com/photo-1615485500704-8e990f9900f7?auto=format&fit=crop&w=700&q=80',desc:'Naturally processed turmeric powder from farmer producers.',tags:['organic','turmeric','farmer']},
      {id:'p2',name:'Homemade Mango Pickle 1kg',category:'Homemade',seller:'Amma Ruchi Home Foods',sellerType:'Homemade',price:349,mrp:399,discount:13,rating:4.8,reviews:94,stock:31,location:'Visakhapatnam',image:'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=700&q=80',desc:'Small-batch traditional mango pickle.',tags:['homemade','pickle']},
      {id:'p3',name:'Premium Basmati Rice 5kg',category:'Grocery',seller:'Jana Kirana',sellerType:'Kirana',price:599,mrp:680,discount:12,rating:4.5,reviews:311,stock:50,location:'Visakhapatnam',image:'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=700&q=80',desc:'Long grain premium basmati rice.',tags:['rice','grocery']},
      {id:'p4',name:'Cold Pressed Groundnut Oil 1L',category:'Farmer Products',seller:'Andhra Naturals',sellerType:'Farmer',price:229,mrp:280,discount:18,rating:4.6,reviews:77,stock:22,location:'Srikakulam',image:'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=700&q=80',desc:'Cold pressed groundnut oil.',tags:['oil','farmer']},
      {id:'p5',name:'LED Smart Bulb 12W',category:'Electronics',seller:'Vizag Electricals',sellerType:'Retailer',price:199,mrp:299,discount:33,rating:4.3,reviews:202,stock:110,location:'Visakhapatnam',image:'https://images.unsplash.com/photo-1509395176047-4a66953fd231?auto=format&fit=crop&w=700&q=80',desc:'Energy efficient smart LED bulb.',tags:['led','home']},
      {id:'p6',name:'Handmade Cotton Tote Bag',category:'Homemade',seller:'Craft Village',sellerType:'Homemade',price:299,mrp:399,discount:25,rating:4.9,reviews:44,stock:16,location:'Vizianagaram',image:'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=700&q=80',desc:'Handmade reusable cotton tote.',tags:['handmade','cotton']},
      {id:'p7',name:'Fresh Tomatoes 1kg',category:'Fresh Produce',seller:'Green Basket Farmer',sellerType:'Farmer',price:48,mrp:60,discount:20,rating:4.4,reviews:67,stock:200,location:'Visakhapatnam',image:'https://images.unsplash.com/photo-1546094096-0df4bcaaa337?auto=format&fit=crop&w=700&q=80',desc:'Fresh local farm tomatoes.',tags:['vegetables','farmer']},
      {id:'p8',name:'Stainless Steel Cookware Set',category:'Home & Kitchen',seller:'National Home Brands',sellerType:'Brand',price:1499,mrp:2199,discount:32,rating:4.5,reviews:181,stock:40,location:'India',image:'https://images.unsplash.com/photo-1584990347449-a7d0c5f5e4c4?auto=format&fit=crop&w=700&q=80',desc:'Multi-piece stainless steel cookware set.',tags:['kitchen','cookware']},
      {id:'p9',name:'A4 Office Paper 500 Sheets',category:'Business Supplies',seller:'Coastal Distributors',sellerType:'Distributor',price:279,mrp:320,discount:13,rating:4.6,reviews:88,stock:500,location:'Visakhapatnam',image:'https://images.unsplash.com/photo-1517842645767-c639042777db?auto=format&fit=crop&w=700&q=80',desc:'Office copier paper for retail and B2B.',tags:['office','b2b']},
      {id:'p10',name:'Natural Neem Soap 100g',category:'Personal Care',seller:'Village Naturals',sellerType:'Manufacturer',price:69,mrp:90,discount:23,rating:4.7,reviews:154,stock:90,location:'India',image:'https://images.unsplash.com/photo-1607006344380-b6775a0824b8?auto=format&fit=crop&w=700&q=80',desc:'Plant-based handmade neem soap.',tags:['soap','natural']}
    ],
    sellers:[
      {id:'s1',name:'Sri Lakshmi FPO',type:'FPO',location:'Visakhapatnam',rating:4.8,status:'approved'},
      {id:'s2',name:'Amma Ruchi Home Foods',type:'Homemade',location:'Visakhapatnam',rating:4.9,status:'approved'},
      {id:'s3',name:'Jana Kirana',type:'Kirana',location:'Visakhapatnam',rating:4.5,status:'approved'},
      {id:'s4',name:'Coastal Distributors',type:'Distributor',location:'Visakhapatnam',rating:4.6,status:'approved'}
    ],
    services:[
      {id:'sv1',name:'Electrician',icon:'⚡',price:'From ₹199',provider:'Vizag Home Services',rating:4.8},
      {id:'sv2',name:'Plumber',icon:'🔧',price:'From ₹199',provider:'QuickFix Local',rating:4.7},
      {id:'sv3',name:'AC Service',icon:'❄️',price:'From ₹399',provider:'CoolCare',rating:4.6},
      {id:'sv4',name:'Computer Repair',icon:'💻',price:'From ₹249',provider:'Tech Local',rating:4.8},
      {id:'sv5',name:'Home Cleaning',icon:'🧹',price:'From ₹499',provider:'CleanPro',rating:4.7},
      {id:'sv6',name:'Painter',icon:'🎨',price:'Get quote',provider:'Local Painters',rating:4.5},
      {id:'sv7',name:'Vehicle Assistance',icon:'🚗',price:'From ₹299',provider:'Auto Assist',rating:4.6},
      {id:'sv8',name:'CCTV Installation',icon:'📹',price:'Get quote',provider:'SecureLocal',rating:4.8}
    ],
    categories:['Grocery','Fresh Produce','Farmer Products','FPO','Homemade','Kirana','Fashion','Electronics','Home & Kitchen','Beauty','Personal Care','Automotive','Business Supplies','Industrial','Services','Recharge & Bills','FASTag','LPG Services'],
    cart:[],wishlist:[],orders:[],campaigns:[],wallet:{balance:0,transactions:[]},tickets:[]
  };
  function load(){try{const d=JSON.parse(localStorage.getItem(KEY));const x=d?Object.assign(seed,d):seed;if(!x.users.some(u=>u.id==='admin'))x.users.push({id:'admin',name:'Super Admin',contact:'admin@janabazar.demo',role:'admin',password:'Admin@123',verified:true});return x}catch(e){seed.users.push({id:'admin',name:'Super Admin',contact:'admin@janabazar.demo',role:'admin',password:'Admin@123',verified:true});return seed}}
  let db=load();
  function save(){localStorage.setItem(KEY,JSON.stringify(db))}
  function money(n){return JB_CONFIG.currency+Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2})}
  function toast(msg){const r=document.getElementById('toast-root'),d=document.createElement('div');d.className='toast';d.textContent=msg;r.appendChild(d);setTimeout(()=>d.remove(),2800)}
  function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function productCard(p){return `<article class="card product"><img class="product-img" src="${p.image}" alt="${esc(p.name)}" onerror="this.src='${img}'"><div class="product-body"><div class="rating">★ ${p.rating} (${p.reviews})</div><h3>${esc(p.name)}</h3><div class="muted">${esc(p.seller)} • ${esc(p.sellerType)}</div><div><span class="price">${money(p.price)}</span> <span class="mrp">${money(p.mrp)}</span> <span class="discount">${p.discount}% off</span></div><div class="toolbar"><button class="btn small" onclick="JB.addCart('${p.id}')">Add to Cart</button><button class="btn small secondary" onclick="JB.product('${p.id}')">View</button><button class="btn small secondary" onclick="JB.wish('${p.id}')">♡</button></div></div></article>`}
  function serviceCard(s){return `<article class="card service-card"><div class="icon-box">${s.icon}</div><h3>${esc(s.name)}</h3><div class="muted">${esc(s.provider)}</div><div>★ ${s.rating} · ${esc(s.price)}</div><button class="btn small" onclick="JB.bookService('${s.id}')">Book Service</button></article>`}
  function sellerCard(s){return `<article class="card seller-card"><div class="icon-box">🏪</div><h3>${esc(s.name)}</h3><div class="chip">${esc(s.type)}</div><p class="muted">📍 ${esc(s.location)}</p><div>★ ${s.rating}</div><button class="btn small secondary" onclick="JB.sellerStore('${s.id}')">View Store</button></article>`}
  const app=document.getElementById('app');
  const JB={
    init(){this.renderCats();this.updateHeader();this.go('home')},
    updateHeader(){document.getElementById('locationText').textContent=db.location;document.getElementById('cartCount').textContent=db.cart.reduce((a,x)=>a+x.qty,0);const u=db.currentUser;document.getElementById('accountBtn').textContent=u?`👤 ${u.name.split(' ')[0]}`:'👤 Login'},
    renderCats(){document.getElementById('categoryStrip').innerHTML=db.categories.map(c=>`<button onclick="JB.search('${c}')">${esc(c)}</button>`).join('')},
    go(route){window.scrollTo({top:0,behavior:'smooth'});if(route==='home')return this.home();if(route==='products')return this.products(db.products,'All Products');if(route==='local')return this.local();if(route==='services')return this.services();if(route==='b2b')return this.b2b();if(route==='cart')return this.cart();if(route==='wishlist')return this.wishlist();if(route==='orders')return this.orders();if(route==='seller')return this.sellerDashboard();if(route==='admin')return this.adminDashboard();if(route==='advertising')return this.advertising();if(route==='support')return this.support();if(route==='policies')return this.policies();if(route==='wallet')return this.wallet();if(route==='utilities')return this.utilities()},
    home(){app.innerHTML=`<div class="container"><section class="hero"><div class="hero-main"><div class="chip" style="width:max-content;background:#dff5e5;color:#095f31">ONE MARKETPLACE • MANY POSSIBILITIES</div><h1>India's People's Marketplace</h1><p>Shop from brands, farmers, FPOs, homemade producers, Kirana stores, manufacturers, distributors and local businesses — plus services and digital utilities.</p><div class="hero-actions"><button class="btn orange" onclick="JB.go('products')">Shop Now</button><button class="btn secondary" onclick="JB.go('local')">Explore Local</button><button class="btn secondary" onclick="JB.openAuth('seller')">Start Selling</button></div></div><div class="hero-side"><div class="stat-card"><span class="muted">Marketplace</span><strong>Multi-Vendor</strong><p>Farmers → Brands → Retailers</p></div><div class="stat-card"><span class="muted">Local</span><strong>Hyperlocal</strong><p>Nearby stores & services</p></div><div class="stat-card"><span class="muted">B2B</span><strong>Bulk Buying</strong><p>RFQ & wholesale workflows</p></div><div class="stat-card"><span class="muted">Utilities</span><strong>24+ Modules</strong><p>Recharge, bills & more</p></div></div></section><div class="section-head"><h2>Shop by ecosystem</h2><button class="btn small secondary" onclick="JB.go('products')">View all</button></div><div class="chips">${['🌾 Farmers','🌱 FPOs','🏠 Homemade','🏪 Kirana','🏭 Manufacturers','🚚 Distributors','🤝 Dealers','📦 Wholesalers','🛍️ Retailers','🛠️ Services'].map(x=>`<button class="chip" onclick="JB.search('${x.slice(2)}')">${x}</button>`).join('')}</div><div class="section-head"><h2>Trending products</h2><button class="btn small secondary" onclick="JB.go('products')">All products</button></div><div class="grid products">${db.products.slice(0,10).map(productCard).join('')}</div><div class="section-head"><h2>Nearby services</h2><button class="btn small secondary" onclick="JB.go('services')">All services</button></div><div class="grid service-grid">${db.services.slice(0,4).map(serviceCard).join('')}</div><div class="section-head"><h2>Digital utilities</h2></div><div class="grid service-grid"><div class="card"><div class="icon-box">📱</div><h3>Recharge & Bills</h3><p class="muted">Mobile, DTH, electricity, broadband and supported billers.</p><button class="btn" onclick="JB.go('utilities')">Open</button></div><div class="card"><div class="icon-box">🚘</div><h3>FASTag</h3><p class="muted">Recharge and supported FASTag services.</p><button class="btn" onclick="JB.utilityTab('fastag')">Open</button></div><div class="card"><div class="icon-box">🔥</div><h3>LPG Services</h3><p class="muted">Supported LPG booking/service workflows.</p><button class="btn" onclick="JB.utilityTab('lpg')">Open</button></div><div class="card"><div class="icon-box">💳</div><h3>JANA Wallet</h3><p class="muted">Wallet, cashback and transaction history.</p><button class="btn" onclick="JB.go('wallet')">Open</button></div></div></div>`},
    products(list,title='Products'){app.innerHTML=`<div class="container"><div class="section-head"><div><h2>${esc(title)}</h2><div class="muted">${list.length} products</div></div><select onchange="JB.filterCategory(this.value)"><option value="">All categories</option>${db.categories.map(c=>`<option>${esc(c)}</option>`).join('')}</select></div><div id="productGrid" class="grid products">${list.map(productCard).join('')||'<div class="empty">No products found.</div>'}</div></div>`},
    filterCategory(c){const list=c?db.products.filter(p=>p.category===c):db.products;this.products(list,c||'All Products')},
    search(q){q=(q||'').trim().toLowerCase();document.getElementById('globalSearch').value=q;if(!q)return this.products(db.products,'All Products');const list=db.products.filter(p=>[p.name,p.category,p.seller,p.sellerType,p.location,...p.tags].join(' ').toLowerCase().includes(q));this.products(list,`Search: ${q}`)},
    local(){const local=db.products.filter(p=>p.location===db.location||p.location==='India');app.innerHTML=`<div class="container"><div class="notice">📍 Showing products and businesses available around <strong>${esc(db.location)}</strong>. Connect a maps/location provider for production-grade geolocation.</div><div class="section-head"><h2>Nearby Stores & Sellers</h2></div><div class="grid seller-grid">${db.sellers.map(sellerCard).join('')}</div><div class="section-head"><h2>Local products</h2></div><div class="grid products">${local.map(productCard).join('')}</div></div>`},
    services(){app.innerHTML=`<div class="container"><div class="hero-main" style="min-height:180px"><h1>Local Services</h1><p>Book verified local service providers. Production verification and payments require provider integrations.</p></div><div class="section-head"><h2>Services near you</h2></div><div class="grid service-grid">${db.services.map(serviceCard).join('')}</div></div>`},
    b2b(){app.innerHTML=`<div class="container"><div class="hero-main" style="min-height:200px"><h1>JANA BAZAR B2B</h1><p>Bulk sourcing for retailers, hotels, offices, institutions and businesses.</p><button class="btn orange" style="width:max-content" onclick="JB.rfq()">Create RFQ</button></div><div class="section-head"><h2>Business marketplace</h2></div><div class="grid products">${db.products.filter(p=>['Distributor','Manufacturer','Brand','Retailer'].includes(p.sellerType)).map(productCard).join('')}</div><div class="section-head"><h2>Distribution chain</h2></div><div class="card"><div class="chips">${['Manufacturer','National Distributor','Regional Distributor','Dealer','Wholesaler','Retailer'].map(x=>`<span class="chip">${x}</span>`).join('')}</div><p class="muted">MOQ, bulk pricing, quote requests, business verification and purchase orders are built into the target architecture.</p></div></div>`},
    cart(){const rows=db.cart.map(i=>{const p=db.products.find(x=>x.id===i.id);return p?`<div class="list-row"><div style="display:flex;gap:12px;align-items:center"><img src="${p.image}" style="width:70px;height:70px;object-fit:cover;border-radius:10px"><div><strong>${esc(p.name)}</strong><div class="muted">${esc(p.seller)}</div><div>${money(p.price)}</div></div></div><div class="qty"><button onclick="JB.qty('${p.id}',-1)">−</button><b>${i.qty}</b><button onclick="JB.qty('${p.id}',1)">+</button><button class="btn small danger" onclick="JB.removeCart('${p.id}')">Remove</button></div></div>`:''}).join('');const total=db.cart.reduce((a,i)=>{const p=db.products.find(x=>x.id===i.id);return a+(p?p.price*i.qty:0)},0);app.innerHTML=`<div class="container"><h2>Your Cart</h2><div class="two-col"><div class="card">${rows||'<div class="empty">Your cart is empty.</div>'}</div><div class="card"><h3>Order Summary</h3><div class="list-row"><span>Items</span><strong>${money(total)}</strong></div><div class="list-row"><span>Delivery</span><strong>${total>=499?'FREE':money(49)}</strong></div><div class="list-row"><span>Total</span><strong>${money(total+(total>=499?0:49))}</strong></div><button class="btn" style="width:100%;margin-top:12px" onclick="JB.checkout()">Proceed to Checkout</button></div></div></div>`},
    addCart(id){const p=db.products.find(x=>x.id===id);if(!p)return;const i=db.cart.find(x=>x.id===id);if(i)i.qty++;else db.cart.push({id,qty:1});save();this.updateHeader();toast('Added to cart')},
    qty(id,d){const i=db.cart.find(x=>x.id===id);if(!i)return;i.qty+=d;if(i.qty<=0)db.cart=db.cart.filter(x=>x.id!==id);save();this.cart();this.updateHeader()},
    removeCart(id){db.cart=db.cart.filter(x=>x.id!==id);save();this.cart();this.updateHeader()},
    wish(id){if(!db.wishlist.includes(id))db.wishlist.push(id);else db.wishlist=db.wishlist.filter(x=>x!==id);save();toast(db.wishlist.includes(id)?'Added to wishlist':'Removed from wishlist')},
    wishlist(){const list=db.products.filter(p=>db.wishlist.includes(p.id));app.innerHTML=`<div class="container"><h2>Wishlist</h2><div class="grid products">${list.map(productCard).join('')||'<div class="empty">No wishlist items yet.</div>'}</div></div>`},
    product(id){const p=db.products.find(x=>x.id===id);if(!p)return;app.innerHTML=`<div class="container"><div class="product-detail"><img class="detail-image" src="${p.image}" alt="${esc(p.name)}"><div><div class="rating">★ ${p.rating} (${p.reviews} reviews)</div><h1>${esc(p.name)}</h1><p class="muted">Sold by <strong>${esc(p.seller)}</strong> · ${esc(p.sellerType)}</p><div><span class="price" style="font-size:34px">${money(p.price)}</span> <span class="mrp">${money(p.mrp)}</span> <span class="discount">${p.discount}% off</span></div><p>${esc(p.desc)}</p><div class="chips"><span class="chip">✓ In stock: ${p.stock}</span><span class="chip">📍 ${esc(p.location)}</span><span class="chip">↩ Eligible return* </span></div><div class="toolbar"><button class="btn orange" onclick="JB.addCart('${p.id}');JB.go('cart')">Buy Now</button><button class="btn" onclick="JB.addCart('${p.id}')">Add to Cart</button><button class="btn secondary" onclick="JB.wish('${p.id}')">♡ Wishlist</button></div><div class="card"><h3>Specifications</h3><p>Category: ${esc(p.category)}</p><p>Seller type: ${esc(p.sellerType)}</p><p>Delivery: location-based estimate</p><p>Warranty/returns: seller/category policy</p></div></div></div><div class="section-head"><h2>Similar products</h2></div><div class="grid products">${db.products.filter(x=>x.category===p.category&&x.id!==p.id).slice(0,5).map(productCard).join('')}</div></div>`},
    checkout(){if(!db.currentUser)return this.openAuth('customer','checkout');if(!db.cart.length)return toast('Cart is empty');this.modal('Checkout',`<form class="form" onsubmit="JB.placeOrder(event)"><label>Delivery Address<input name="address" required value="${esc(db.currentUser.address||'Visakhapatnam')}" /></label><label>Payment<select name="payment"><option>COD (Demo)</option><option>UPI (Provider required)</option><option>Card (Provider required)</option><option>JANA Wallet</option></select></label><div class="notice">Demo checkout is local-only. Real payment requires a gateway and verified backend webhook.</div><button class="btn">Place Order</button></form>`)},
    placeOrder(e){e.preventDefault();const f=new FormData(e.target);const subtotal=db.cart.reduce((a,i)=>{const p=db.products.find(x=>x.id===i.id);return a+(p?p.price*i.qty:0)},0);const total=subtotal+(subtotal>=499?0:49);const order={id:'JB'+Date.now().toString().slice(-8),date:new Date().toISOString(),user:db.currentUser.id,items:db.cart.map(x=>({...x})),total,address:f.get('address'),payment:f.get('payment'),status:'PLACED',deliveryOtp:'1234'};db.orders.unshift(order);db.cart=[];save();this.closeModal();this.updateHeader();toast(`Order ${order.id} placed`);this.orders()},
    orders(){const u=db.currentUser;const list=u?db.orders.filter(o=>o.user===u.id):[];app.innerHTML=`<div class="container"><div class="section-head"><h2>My Orders</h2>${u?'':'<button class="btn" onclick="JB.openAuth()">Login</button>'}</div>${u?(list.map(o=>`<div class="card" style="margin-bottom:12px"><div class="list-row"><strong>${o.id}</strong><span class="badge approved">${o.status}</span></div><div class="muted">${new Date(o.date).toLocaleString('en-IN')} · ${o.payment}</div><div class="list-row"><span>Total</span><strong>${money(o.total)}</strong></div><div class="toolbar"><button class="btn small secondary" onclick="JB.orderDetail('${o.id}')">Track / View</button></div></div>`).join('')||'<div class="empty">No orders yet.</div>'):'<div class="empty">Login to view orders.</div>'}</div>`},
    orderDetail(id){const o=db.orders.find(x=>x.id===id);if(!o)return;this.modal('Order '+o.id,`<div class="card"><p><strong>Status:</strong> ${o.status}</p><p><strong>Delivery OTP:</strong> ${o.deliveryOtp} <span class="muted">(demo)</span></p><p><strong>Address:</strong> ${esc(o.address)}</p><h4>Timeline</h4><div class="chips">${['PLACED','CONFIRMED','PACKED','SHIPPED','OUT_FOR_DELIVERY','DELIVERED'].map((x,i)=>`<span class="chip">${i<1?'✓ ':''}${x}</span>`).join('')}</div></div>`)},
    wallet(){const w=db.wallet;app.innerHTML=`<div class="container"><div class="two-col"><div class="card"><div class="muted">JANA Wallet Balance</div><div class="price" style="font-size:42px">${money(w.balance)}</div><div class="toolbar"><button class="btn" onclick="JB.addMoney()">Add Money</button><button class="btn secondary" onclick="JB.go('utilities')">Recharge & Bills</button></div></div><div class="card"><h3>Wallet security</h3><p>Real wallet money requires an authorized payment provider, secure backend ledger and applicable compliance.</p></div></div><div class="section-head"><h2>Transactions</h2></div><div class="card">${w.transactions.map(t=>`<div class="list-row"><span>${esc(t.text)}</span><strong>${t.amount>=0?'+':''}${money(t.amount)}</strong></div>`).join('')||'<div class="empty">No transactions.</div>'}</div></div>`},
    addMoney(){this.modal('Add Money',`<form class="form" onsubmit="JB.walletAdd(event)"><input name="amount" type="number" min="1" placeholder="Amount" required><div class="notice">Demo wallet only. Connect a real payment provider before accepting money.</div><button class="btn">Continue</button></form>`)},
    walletAdd(e){e.preventDefault();const amount=Number(new FormData(e.target).get('amount'));db.wallet.balance+=amount;db.wallet.transactions.unshift({text:'Demo wallet credit',amount,date:new Date().toISOString()});save();this.closeModal();this.wallet();toast('Demo wallet credited')},
    utilities(){app.innerHTML=`<div class="container"><h2>JANA Utilities</h2><div class="tabs"><button class="active" onclick="JB.utilityTab('recharge')">Recharge & Bills</button><button onclick="JB.utilityTab('fastag')">FASTag</button><button onclick="JB.utilityTab('lpg')">LPG</button></div><div id="utilityBox"></div></div>`;this.utilityTab('recharge')},
    utilityTab(tab){if(!document.getElementById('utilityBox')){this.go('utilities');return}const forms={recharge:`<div class="card"><h3>Recharge & Bill Payments</h3><form class="form" onsubmit="JB.utilitySubmit(event,'recharge')"><select name="type"><option>Mobile Recharge</option><option>DTH</option><option>Electricity</option><option>Water</option><option>Broadband</option></select><input name="number" placeholder="Mobile / Consumer Number" required><input name="amount" type="number" placeholder="Amount" required><button class="btn">Proceed</button></form></div>`,fastag:`<div class="card"><h3>FASTag</h3><form class="form" onsubmit="JB.utilitySubmit(event,'fastag')"><input name="vehicle" placeholder="Vehicle number" required><input name="amount" type="number" placeholder="Recharge amount" required><button class="btn">Proceed</button></form></div>`,lpg:`<div class="card"><h3>LPG Services</h3><form class="form" onsubmit="JB.utilitySubmit(event,'lpg')"><input name="consumer" placeholder="Consumer number" required><select name="service"><option>Refill booking</option><option>Service information</option><option>Distributor support</option></select><button class="btn">Continue</button></form></div>`};document.getElementById('utilityBox').innerHTML=forms[tab];toast(tab.toUpperCase()+' module opened')},
    utilitySubmit(e,type){e.preventDefault();this.closeModal();toast(`${type.toUpperCase()} demo request submitted. Provider integration required for real transaction.`)},
    sellerStore(id){const s=db.sellers.find(x=>x.id===id);if(!s)return;const list=db.products.filter(p=>p.seller===s.name);app.innerHTML=`<div class="container"><div class="card"><h1>🏪 ${esc(s.name)}</h1><div class="chips"><span class="chip">${esc(s.type)}</span><span class="chip">📍 ${esc(s.location)}</span><span class="chip">★ ${s.rating}</span></div><p>Verified seller storefront. Business details, products, offers and reviews appear here.</p></div><div class="section-head"><h2>Store Products</h2></div><div class="grid products">${list.map(productCard).join('')||'<div class="empty">No products listed.</div>'}</div></div>`},
    sellerDashboard(){const u=db.currentUser;if(!u||!['seller','delivery','service','b2b'].includes(u.role))return this.openAuth('seller');app.innerHTML=`<div class="container"><div class="dashboard"><aside class="sidebar card"><button class="active">📊 Overview</button><button onclick="JB.sellerProducts()">📦 Products</button><button onclick="JB.sellerOrders()">🧾 Orders</button><button onclick="JB.sellerFinance()">💰 Finance</button><button onclick="JB.go('advertising')">📢 Advertising</button><button onclick="JB.go('support')">🎧 Support</button></aside><section class="dashboard-content"><div class="metric-grid"><div class="metric">Orders<strong>${db.orders.length}</strong></div><div class="metric">Products<strong>${db.products.filter(p=>p.seller===u.name).length}</strong></div><div class="metric">Rating<strong>4.7</strong></div><div class="metric">Settlement<strong>${money(0)}</strong></div></div><div class="section-head"><h2>Seller control center</h2><button class="btn" onclick="JB.sellerProducts()">Manage Products</button></div><div class="three-col"><div class="card"><h3>Seller verification</h3><p class="muted">KYC, GST, bank and applicable licences.</p><span class="badge approved">Demo Approved</span></div><div class="card"><h3>Storefront</h3><p class="muted">Manage your public store profile and catalogue.</p><button class="btn small secondary" onclick="JB.sellerStore('s1')">Preview</button></div><div class="card"><h3>Ads</h3><p class="muted">Create sponsored campaigns.</p><button class="btn small" onclick="JB.go('advertising')">Open</button></div></div></section></div></div>`},
    sellerProducts(){const u=db.currentUser;const list=db.products.filter(p=>p.seller===u.name);app.innerHTML=`<div class="container"><div class="section-head"><h2>Product Management</h2><button class="btn" onclick="JB.addProduct()">+ Add Product</button></div><div class="card table-wrap"><table class="table"><thead><tr><th>Product</th><th>Price</th><th>Stock</th><th>Category</th><th>Action</th></tr></thead><tbody>${list.map(p=>`<tr><td>${esc(p.name)}</td><td>${money(p.price)}</td><td>${p.stock}</td><td>${esc(p.category)}</td><td><button class="btn small secondary" onclick="JB.product('${p.id}')">View</button></td></tr>`).join('')||'<tr><td colspan="5">No products yet.</td></tr>'}</tbody></table></div></div>`},
    addProduct(){this.modal('Add Product',`<form class="form" onsubmit="JB.saveProduct(event)"><input name="name" placeholder="Product name" required><select name="category">${db.categories.map(c=>`<option>${esc(c)}</option>`).join('')}</select><input name="price" type="number" min="0" placeholder="Selling price" required><input name="mrp" type="number" min="0" placeholder="MRP" required><input name="stock" type="number" min="0" placeholder="Stock" required><input name="image" placeholder="Image URL (optional)"><textarea name="desc" placeholder="Description"></textarea><button class="btn">Publish Product</button></form>`)},
    saveProduct(e){e.preventDefault();const f=new FormData(e.target),u=db.currentUser;db.products.unshift({id:'p'+Date.now(),name:f.get('name'),category:f.get('category'),seller:u.name,sellerType:'Seller',price:Number(f.get('price')),mrp:Number(f.get('mrp')),discount:Math.max(0,Math.round((1-Number(f.get('price'))/Number(f.get('mrp')))*100)),rating:0,reviews:0,stock:Number(f.get('stock')),location:db.location,image:f.get('image')||img,desc:f.get('desc')||'',tags:[]});save();this.closeModal();this.sellerProducts();toast('Product published')},
    sellerOrders(){this.orders()},sellerFinance(){this.wallet()},
    advertising(){app.innerHTML=`<div class="container"><div class="hero-main" style="min-height:180px"><h1>Advertising Center</h1><p>Sponsored products, local promotions, store banners and campaign analytics.</p><button class="btn orange" style="width:max-content" onclick="JB.createCampaign()">Create Campaign</button></div><div class="section-head"><h2>Campaigns</h2></div><div class="card table-wrap"><table class="table"><thead><tr><th>Campaign</th><th>Type</th><th>Budget</th><th>Status</th></tr></thead><tbody>${db.campaigns.map(c=>`<tr><td>${esc(c.name)}</td><td>${esc(c.type)}</td><td>${money(c.budget)}</td><td><span class="badge approved">${c.status}</span></td></tr>`).join('')||'<tr><td colspan="4">No campaigns.</td></tr>'}</tbody></table></div></div>`},
    createCampaign(){this.modal('Create Advertising Campaign',`<form class="form" onsubmit="JB.saveCampaign(event)"><input name="name" placeholder="Campaign name" required><select name="type"><option>Sponsored Product</option><option>Local Store Promotion</option><option>Banner</option><option>Category Promotion</option></select><input name="budget" type="number" min="100" placeholder="Budget" required><button class="btn">Create Campaign</button></form>`)},
    saveCampaign(e){e.preventDefault();const f=new FormData(e.target);db.campaigns.push({name:f.get('name'),type:f.get('type'),budget:Number(f.get('budget')),status:'DRAFT'});save();this.closeModal();this.advertising();toast('Campaign created')},
    adminDashboard(){const u=db.currentUser;if(!u||u.role!=='admin')return this.openAuth('admin');app.innerHTML=`<div class="container"><div class="dashboard"><aside class="sidebar card"><button class="active">📊 Dashboard</button><button onclick="JB.adminUsers()">👥 Customers</button><button onclick="JB.adminSellers()">🏪 Sellers</button><button onclick="JB.adminProducts()">📦 Products</button><button onclick="JB.adminOrders()">🧾 Orders</button><button onclick="JB.advertising()">📢 Ads</button><button onclick="JB.go('utilities')">💳 Utilities</button><button onclick="JB.go('support')">🎧 Support</button></aside><section class="dashboard-content"><div class="metric-grid"><div class="metric">Customers<strong>${db.users.filter(x=>x.role==='customer').length}</strong></div><div class="metric">Sellers<strong>${db.sellers.length}</strong></div><div class="metric">Products<strong>${db.products.length}</strong></div><div class="metric">Orders<strong>${db.orders.length}</strong></div></div><div class="section-head"><h2>Marketplace control center</h2></div><div class="three-col"><div class="card"><h3>Seller approvals</h3><p>Review KYC, business and applicable compliance documents.</p><button class="btn small" onclick="JB.adminSellers()">Review</button></div><div class="card"><h3>Catalog moderation</h3><p>Approve products, categories, offers and prohibited content.</p><button class="btn small" onclick="JB.adminProducts()">Open</button></div><div class="card"><h3>Audit & security</h3><p>Role-based permissions, login history and sensitive-action logs.</p><button class="btn small secondary" onclick="JB.securityInfo()">View</button></div></div></section></div></div>`},
    adminUsers(){app.innerHTML=`<div class="container"><h2>Customer Management</h2><div class="card table-wrap"><table class="table"><thead><tr><th>Name</th><th>Contact</th><th>Role</th><th>Verified</th></tr></thead><tbody>${db.users.map(u=>`<tr><td>${esc(u.name)}</td><td>${esc(u.contact)}</td><td>${u.role}</td><td><span class="badge approved">${u.verified?'YES':'NO'}</span></td></tr>`).join('')||'<tr><td colspan="4">No registered users.</td></tr>'}</tbody></table></div></div>`},
    adminSellers(){app.innerHTML=`<div class="container"><div class="section-head"><h2>Seller Management</h2></div><div class="card table-wrap"><table class="table"><thead><tr><th>Seller</th><th>Type</th><th>Location</th><th>Status</th><th>Action</th></tr></thead><tbody>${db.sellers.map(s=>`<tr><td>${esc(s.name)}</td><td>${esc(s.type)}</td><td>${esc(s.location)}</td><td><span class="badge ${s.status==='approved'?'approved':'pending'}">${s.status}</span></td><td>${s.status!=='approved'?`<button class="btn small" onclick="JB.approveSeller('${s.id}')">Approve</button>`:'Approved'}</td></tr>`).join('')}</tbody></table></div></div>`},
    approveSeller(id){const s=db.sellers.find(x=>x.id===id);if(s)s.status='approved';save();this.adminSellers();toast('Seller approved')},
    adminProducts(){app.innerHTML=`<div class="container"><h2>Catalog Management</h2><div class="card table-wrap"><table class="table"><thead><tr><th>Product</th><th>Seller</th><th>Category</th><th>Stock</th><th>Action</th></tr></thead><tbody>${db.products.map(p=>`<tr><td>${esc(p.name)}</td><td>${esc(p.seller)}</td><td>${esc(p.category)}</td><td>${p.stock}</td><td><button class="btn small secondary" onclick="JB.product('${p.id}')">View</button></td></tr>`).join('')}</tbody></table></div></div>`},
    adminOrders(){this.orders()},
    securityInfo(){this.modal('Security Architecture',`<ul><li>Role-based access control</li><li>OTP expiry and rate limits</li><li>Password reset with verified recovery</li><li>Session invalidation on password reset</li><li>Admin MFA</li><li>Audit logs</li><li>Server-side payment verification</li><li>No secret provider keys in frontend</li></ul>`)},
    support(){app.innerHTML=`<div class="container"><div class="two-col"><div class="card"><h2>Help & Support</h2><form class="form" onsubmit="JB.ticket(event)"><input name="subject" placeholder="Subject" required><select name="type"><option>Order</option><option>Payment</option><option>Seller</option><option>Delivery</option><option>Service</option><option>Account</option></select><textarea name="message" rows="5" placeholder="Describe your issue" required></textarea><button class="btn">Create Ticket</button></form></div><div class="card"><h2>Help Center</h2><p>Order tracking, returns, refunds, seller issues, payments and account recovery.</p><div class="notice">Production deployment should connect email/WhatsApp/SMS support providers.</div></div></div></div>`},
    ticket(e){e.preventDefault();const f=new FormData(e.target);db.tickets.unshift({id:'T'+Date.now().toString().slice(-7),subject:f.get('subject'),type:f.get('type'),message:f.get('message'),status:'OPEN'});save();toast('Support ticket created');e.target.reset()},
    policies(){app.innerHTML=`<div class="container"><div class="card"><h2>Policies</h2><h3>Terms & Conditions</h3><p>Marketplace terms must be finalized by the business and legal advisor before launch.</p><h3>Privacy</h3><p>Production version must document data collection, retention, consent, security and user rights.</p><h3>Returns & Refunds</h3><p>Policies vary by seller/category and must be configured before production.</p><h3>Seller Terms</h3><p>Seller onboarding should include KYC, applicable tax/licence obligations, prohibited products and settlement terms.</p></div></div>`},
    rfq(){this.modal('Create B2B RFQ',`<form class="form" onsubmit="event.preventDefault();JB.closeModal();toast('RFQ created in demo mode')"><input placeholder="Business name" required><input placeholder="Product / requirement" required><input type="number" placeholder="Quantity" required><textarea placeholder="Additional requirements"></textarea><button class="btn">Submit RFQ</button></form>`)},
    bookService(id){const s=db.services.find(x=>x.id===id);if(!s)return;this.modal('Book '+s.name,`<form class="form" onsubmit="event.preventDefault();JB.closeModal();toast('Service booking created in demo mode')"><input placeholder="Name" required><input placeholder="Mobile" required><input type="date" required><input type="time" required><textarea placeholder="Service details"></textarea><button class="btn">Request Booking</button></form>`)},
    pickLocation(){this.modal('Choose Location',`<form class="form" onsubmit="JB.saveLocation(event)"><select name="location"><option>Visakhapatnam</option><option>Srikakulam</option><option>Vizianagaram</option><option>Rajamahendravaram</option><option>Hyderabad</option><option>Bengaluru</option></select><button class="btn">Save Location</button></form>`)},
    saveLocation(e){e.preventDefault();db.location=new FormData(e.target).get('location');save();this.closeModal();this.updateHeader();toast('Location updated');this.go('local')},
    voiceSearch(){if(!('webkitSpeechRecognition' in window||'SpeechRecognition' in window))return toast('Voice search is not supported in this browser');const R=window.SpeechRecognition||window.webkitSpeechRecognition,r=new R();r.lang='te-IN';r.onresult=e=>this.search(e.results[0][0].transcript);r.start()},
    openAuth(role='customer',after=''){const isLogin=role!=='register';this.modal('JANA BAZAR Account',`<div class="tabs"><button id="loginTab" class="active" onclick="JB.authView('login','${role}','${after}')">Login</button><button onclick="JB.authView('register','${role}','${after}')">Register</button></div><div id="authBox" style="margin-top:14px"></div>`);this.authView('login',role,after)},
    authView(view,role='customer',after=''){document.getElementById('authBox').innerHTML=view==='login'?`<form class="form" onsubmit="JB.login(event,'${role}','${after}')"><input name="contact" placeholder="Mobile or Email" required><input name="password" type="password" placeholder="Password" required><button class="btn">Login</button><button type="button" class="btn secondary" onclick="JB.forgot('${role}')">Forgot Password?</button><div class="notice">Demo OTP: <strong>${JB_CONFIG.demoOtp}</strong>. Production requires a real OTP provider.</div></form>`:`<form class="form" onsubmit="JB.register(event,'${role}')"><input name="name" placeholder="Full name / Business name" required><input name="contact" placeholder="Mobile or Email" required><input name="password" type="password" minlength="6" placeholder="Password (min 6)" required><select name="role"><option value="customer">Customer</option><option value="seller">Seller</option><option value="b2b">B2B Buyer</option><option value="service">Service Provider</option><option value="delivery">Delivery Partner</option><option value="admin">Admin (Invite Only)</option></select><label><input type="checkbox" required> I agree to the applicable terms.</label><button class="btn">Register & Verify OTP</button><div class="notice">Demo OTP: <strong>${JB_CONFIG.demoOtp}</strong></div></form>`},
    login(e,requestedRole,after){e.preventDefault();const f=new FormData(e.target),contact=f.get('contact'),password=f.get('password');let u=db.users.find(x=>x.contact===contact&&x.password===password);if(!u&&contact==='admin@janabazar.demo'&&password==='Admin@123'){u={id:'admin',name:'Super Admin',contact,role:'admin',password,verified:true};db.users.push(u);save()}if(!u)return toast('Invalid credentials. Use Register or demo admin: admin@janabazar.demo / Admin@123');db.currentUser=u;save();this.closeModal();this.updateHeader();toast('Login successful');if(after==='checkout')this.checkout();else if(u.role==='admin')this.go('admin');else if(['seller','service','delivery','b2b'].includes(u.role))this.go('seller');else this.go('home')},
    register(e,requestedRole){e.preventDefault();const f=new FormData(e.target),role=f.get('role');if(role==='admin'&&prompt('Enter admin invitation code:')!=='JB-ADMIN-INVITE-2026')return toast('Admin registration requires a valid invitation code');if(db.users.some(x=>x.contact===f.get('contact')))return toast('Account already exists');this.modal('Verify OTP',`<form class="form" onsubmit="JB.verifyRegistration(event,'${esc(f.get('name'))}','${esc(f.get('contact'))}','${esc(f.get('password'))}','${role}')"><p>OTP sent to <strong>${esc(f.get('contact'))}</strong>.</p><input name="otp" inputmode="numeric" placeholder="Enter OTP" required><div class="notice">Demo OTP: <strong>${JB_CONFIG.demoOtp}</strong></div><button class="btn">Verify & Create Account</button></form>`)},
    verifyRegistration(e,name,contact,password,role){e.preventDefault();const otp=new FormData(e.target).get('otp');if(otp!==JB_CONFIG.demoOtp)return toast('Invalid OTP');const u={id:'u'+Date.now(),name,contact,password,role,verified:true,address:db.location};db.users.push(u);if(role==='seller'){db.sellers.push({id:'s'+Date.now(),name,type:'Seller',location:db.location,rating:0,status:'pending'})}db.currentUser=u;save();this.closeModal();this.updateHeader();toast('Account created and verified');if(role==='seller')this.go('seller');else this.go('home')},
    forgot(role){this.modal('Forgot Password',`<form class="form" onsubmit="JB.sendReset(event,'${role}')"><input name="contact" placeholder="Registered mobile/email" required><button class="btn">Send OTP</button><div class="notice">Demo OTP: <strong>${JB_CONFIG.demoOtp}</strong></div></form>`)},
    sendReset(e,role){e.preventDefault();const c=new FormData(e.target).get('contact');if(!db.users.some(x=>x.contact===c)&&c!=='admin@janabazar.demo')return toast('Account not found');this.modal('Verify OTP & Reset Password',`<form class="form" onsubmit="JB.resetPassword(event,'${esc(c)}')"><input name="otp" placeholder="OTP" required><input name="password" type="password" minlength="6" placeholder="New password" required><input name="confirm" type="password" minlength="6" placeholder="Confirm password" required><div class="notice">Demo OTP: <strong>${JB_CONFIG.demoOtp}</strong></div><button class="btn">Reset Password</button></form>`)},
    resetPassword(e,contact){e.preventDefault();const f=new FormData(e.target);if(f.get('otp')!==JB_CONFIG.demoOtp)return toast('Invalid OTP');if(f.get('password')!==f.get('confirm'))return toast('Passwords do not match');const u=db.users.find(x=>x.contact===contact);if(!u)return toast('Admin recovery requires production MFA setup');u.password=f.get('password');save();this.closeModal();toast('Password updated. Please login again.');this.openAuth(u.role)},
    modal(title,body){document.getElementById('modal-root').innerHTML=`<div class="modal-backdrop" onclick="if(event.target===this)JB.closeModal()"><div class="modal"><div class="modal-head"><h3>${esc(title)}</h3><button class="close" onclick="JB.closeModal()">×</button></div><div class="modal-body">${body}</div></div></div>`},
    closeModal(){document.getElementById('modal-root').innerHTML=''}
  };
  window.JB=JB;window.addEventListener('DOMContentLoaded',()=>JB.init());
})();
